# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank
first_name: Robert
middle_name: 
last_name: Fofrich Navarro
position: Postdoctoral Research Associate
institution:
  name: Dartmouth College
  url: https://www.dartmouth.edu
  logo: D-Pine_RGB.png
  dark_logo: D-Pine_Black.png
  website: https://jsmankin.github.io

social_links:
  linkedin: https://www.linkedin.com/in/robertfofrich/
  github: https://github.com/rfofrich
  google_scholar: https://scholar.google.com/citations?user=5_uvPIIAAAAJ&hl=en
  orcid: https://orcid.org/my-orcid?orcid=0000-0001-6418-3692
  researchgate: https://www.researchgate.net/profile/Robert-Fofrich-2
  bluesky: https://bsky.app/profile/robertfofrich.bsky.social

address: 33 Tuck Mall, Hanover, NH 03755, USA
email: robertfofrich@dartmouth.edu

description: >
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
keywords: Robert Fofrich, academic-website, portfolio-website
lang: en
icon: D-Pine_RGB.png

url: https://rfofrich.github.io
baseurl: ""
last_updated: false
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

external_services:
  github_readme_stats_url: https://github-readme-stats.vercel.app
  github_profile_trophy_url: https://github-profile-trophy.vercel.app

# -----------------------------------------------------------------------------
# Layout & Blog
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false
socials_in_search: false
posts_in_search: false
bib_search: false
max_width: 930px

blog_name: al-folio
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/
lsi: false

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Analytics
# -----------------------------------------------------------------------------

google_analytics: G-9C18VP2YFH
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:

google_site_verification:-ws2olRiFkA0MROGMtQgSln31NNjyy2YzvF018YUfnM
bing_site_verification:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true
  teachings:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_scripts"]
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
keep_files:
  - CNAME
  - .nojekyll
  - BingSiteAuth.xml

plugins:
  - jekyll-3rd-party-libraries
  - jekyll-archives-v2
  - jekyll-cache-bust
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-socials
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# -----------------------------------------------------------------------------
# Third-party libraries (must match plugin jekyll-3rd-party-libraries)
# -----------------------------------------------------------------------------

third_party_libraries:
  download: false
  bootstrap-table:
    version: "1.22.4"
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@1.22.4/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@1.22.4/dist/bootstrap-table.min.js"
  chartjs:
    version: "4.4.1"
    url:
      js: "https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"
  d3:
    version: "7.8.5"
    url:
      js: "https://cdn.jsdelivr.net/npm/d3@7.8.5/dist/d3.min.js"
  mathjax:
    version: "3.2.2"
    url:
      js: "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js"

# -----------------------------------------------------------------------------
# Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Fofrich Navarro]
  first_name: [Robert]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending


# -----------------------------------------------------------------------------
# Resume JSON
# -----------------------------------------------------------------------------

plugins_config:
  jekyll-get-json:
    - data: resume
      json: "assets/json/resume.json"
